export const SiDo = [
  { label: '시,도를 선택해주세요', value: '0' },
  { label: '서울시', value: '11' },
];

export const GunGu = [
  { label: '군,구를 선택해주세요', value: '0' },
  { label: '종로구', value: '110' },
  { label: '중구', value: '140' },
  { label: '용산구', value: '170' },
  { label: '성동구', value: '200' },
  { label: '광진구', value: '215' },
  { label: '동대문구', value: '230' },
  { label: '중랑구', value: '260' },
  { label: '성북구', value: '290 ' },
  { label: '강북구', value: '305' },
  { label: '도봉구', value: '320' },
  { label: '노원구', value: '350' },
  { label: '은평구', value: '380' },
  { label: '서대문구', value: '410' },
  { label: '마포구', value: '440' },
  { label: '양천구', value: '470' },
  { label: '강서구', value: '500' },
  { label: '구로구', value: '530' },
  { label: '금천구', value: '545' },
  { label: '영등포구', value: '560' },
  { label: '동작구', value: '590' },
  { label: '관악구', value: '620' },
  { label: '서초구', value: '650' },
  { label: '강남구', value: '680' },
  { label: '송파구', value: '710' },
  { label: '강동구', value: '740' },
];
